[package]
name = "rust"
version = "0.1.0"
authors = ["James Mussett <jamesmussett@gmail.com>"]

[dependencies]
portaudio = "0.7.0"
num-derive = "0.2"
num-traits = "0.2"
crossbeam-channel = "0.3"
audio_thread_priority = "0.3"