[package]
name = "modulardsp_native"
version = "0.1.0"
authors = ["James Mussett <jamesmussett@gmail.com>"]
edition = "2018"

[dependencies]
portaudio = "0.7.0"
crossbeam-channel = "0.3"
portmidi = "0.2.4"
modulardsp = { path = "../" }